# SSL Pretraining Config for PhysioNet 2020
data:
  dataset_name: "cinc2020"
  data_dir: "/kaggle/input/datasets/gundetisiddarth/physionet-2020/phsionet_2020/"
  score_path: "/kaggle/input/datasets/gundetisiddarth/physionet-2020/phsionet_2020/dx_mapping_scored.csv"
  split: "0"
  target_fs: 257
  seq_length: 4096
  lead2_sec: 15.94
  morphology_sec: 15.94
  num_classes: 24

training:
  batch_size: 64
  num_workers: 4
  epochs: 2
  learning_rate: 0.0001
  weight_decay: 0.00001
  device: "cuda"

ssl:
  temperature: 0.1

checkpoints:
  save_dir: "/kaggle/working/checkpoints"
  best_ssl_teacher: "checkpoints/cinc2020_best_ssl_teacher.pth"
  best_projection_head: "checkpoints/cinc2020_best_projection_head.pth"
