data:
  dataset_name: cinc2020
  data_dir: D:\Datasets\phsionet_2020\
  score_path: D:\Datasets\phsionet_2020\dx_mapping_scored.csv
  split: '0'
  target_fs: 257
  seq_length: 4096
  lead2_sec: 15.94
  morphology_sec: 15.94
training:
  batch_size: 64
  num_workers: 8
  epochs: 50
  learning_rate: 0.0005
  weight_decay: 1.0e-05
  device: cuda
  monitor_metric: cm_score
  num_classes: 24
  temperature: 2.0
  alpha: 0.5
  beta: 0.3
  gamma: 0.2
checkpoints:
  save_dir: D:\ECG_SSL_KD\checkpoints
  teacher_checkpoint: D:/ECG_SSL_KD/checkpoints/finetune_20260707_103620/best_teacher_finetuned.pth
  teacher_weights: D:/ECG_SSL_KD/checkpoints/finetune_20260707_082840/best_teacher_finetuned.pth
