# SSL Pretraining Config
data:
  data_dir: "D:\\Datasets\\PTBXL\\"
  score_path: "/scratch/physionet2020/dx_mapping_scored.csv"
  split: "0"

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.0003
  weight_decay: 0.00001
  temperature: 0.1
  device: "cuda"

checkpoints:
  save_dir: "checkpoints/"
  best_ssl_teacher: "checkpoints/best_ssl_teacher.pth"
  best_projection_head: "checkpoints/best_projection_head.pth"
